### ISSUE TITLE
Login Fail often when connection < WiFi

### ISSUE THREAD

**Issue by Voxar** [nevyn/spot#11]
Login fails very often on connections lower then WiFi. 
If you are on 3G and open a safari just before Spot there is greater chance of success

**Comment by nevyn** [comment]
I theorize that this is because the modem doesn't open unless you use an Apple API for accessing the network; if we just add an NSURLRequest to google or something or launch I think it'd work better.

**Comment by Voxar** [comment]
Fixed by doing some kind of NSURLRequest (StringWithContents... to google I think :P)
