### ISSUE TITLE
Not working with current spotify API

### ISSUE THREAD

**Issue by estock** [nevyn/spot#21]
After compiling and running in the simulator, I'm getting  "client upgrade required" apparently despotify_init_client() has been updated to require a fourth parameter, "use_cache". I'm not sure how easily this can be updated, seems lke there have been a number of changes

**Comment by nevyn** [comment]
Yes, this project is dead; I'm working on the official client now. Feel free to merge in the latest despotify and it'll probably work again; gimme a pull request when you're done and I'll merge it in.
