### ISSUE TITLE
compile errors

### ISSUE THREAD

**Issue by mythz** [nevyn/spot#9]
Hi I'm having some problems trying to link against openssl to complile your xcode-project:
../spot/Vendor/despotify/src/lib/session.h:11:24: error: openssl/dh.h: No such file or directory

I have got openssl installed (for osx) and are available under /usr/include/openssl, although I don't have a build for the iphone (which I'm guessing is my problem). I've had a look at all the iPhone frameworks and it doesn't look like any of them come with openssl installed?

I also noticed that you have included libssl.a and libcrypto.a which may have include the openssl dependancy I'm after although I'm not sure why it still has compliation problems.

What have you done to get openssl installed on your pc?

**Comment by nevyn** [comment]
I've bundled the openssl headers in the repos. That's the problem, not the linking; I have made an iphone/macos universal binary in the Vendor folder. Made sense to have the headers with the lib.

Does it work for you now?
